# Generated by Django 6.0.2 on 2026-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Primer', 'Primer'), ('Waterproofing', 'Waterproofing')], max_length=100),
        ),
    ]
