# Generated by Django 6.0.2 on 2026-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Asian Paints', 'Asian Paints'), ('Birla Opus', 'Birla Opus'), ('Surfa Coat', 'Surfa Coat Paints'), ('Rajyog', 'Rajyog Paints')], max_length=100),
        ),
    ]
